### ISSUE TITLE
Error when inserting an audio clip

### ISSUE THREAD

**Issue by thlsn** [AwesomeTTS/awesometts-anki-addon#102] opened 2020-06-22 00:13 UTC
I don't know why this happens in my anki when trying to add audio to my cards. After adding some audios in different cards, this always happens and the only way to correct is to restart anki.

Informação de Debug:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-21 19:35:35

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 518, in _onBridgeCmd
  File "aqt\editor.py", line 408, in onBridgeCmd
  File "C:\Users\XX\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\common.py", line 126, in _show
    self._instance.show()
  File "C:\Users\XX\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\generator.py", line 729, in show
    super(EditorGenerator, self).show(*args, **kwargs)
  File "C:\Users\XX\AppData\Roaming\Anki2\addons21\1436550454\awesometts\gui\base.py", line 404, in show
    dropdown = self.findChild(QtWidgets.QComboBox, 'service')
RuntimeError: wrapped C/C++ object of type EditorGenerator has been deleted

**Comment by lucwastiaux** [comment] 2020-06-22 01:21
Can you share your deck? Which service and which voice are you using?

**Comment by thlsn** [comment] 2020-06-22 23:36
This happens with all the decks I use. The voice I usually use is Google Cloud Text-to-Speech's en-US-Wavenet-D [default], but the error occurs before the plugin opens, when I click on the icon inside a card. This is strange because it happens after adding some cards with audio and it doesn't work until I restart Anki.

**Comment by lucwastiaux** [comment] 2020-06-25 03:54
Does this ever happen when you use the batch generator (select cards, AwesomeTTS -> Add audio to selected) ? Or it happens only when you're trying to add audio at the same time as you add a card ?

**Comment by thlsn** [comment] 2020-06-25 23:59
Bro, I didn't even know it was possible to add multiple audio at the same time. lol Thanks for the advice!
But yes, when I try to add audio at the same time that I add a card, it happens. Now that I know of the possibility of adding several audios at the same time, I will test if the error happen in this case.

**Comment by lucwastiaux** [comment] 2020-06-26 00:21
I think you'll find it's much more convenient to add your audio in batches. That being said the bug you found should be fixed. I'll keep looking into it.

**Comment by thlsn** [comment] 2020-06-26 00:29
Thank you, @lucwastiaux . It's certainly much better to add audio in batches. Thanks in advance for fixing the bug and for quick responses. I hope you and your family are well and safe.

**Comment by lucwastiaux** [comment] 2020-06-26 01:14
Cool, if awesometts is working well for you otherwise, please leave a review!

**Comment by lucwastiaux** [comment] 2020-07-24 08:32
Another similar issue: https://forums.ankiweb.net/t/awesometts-cause-an-error-when-used-in-a-new-note-form/921/5

**Comment by lucwastiaux** [comment] 2020-08-27 02:33
I need someone to record a screen capture showing this bug. I'm unable to reproduce it.

**Comment by lucwastiaux** [comment] 2020-08-28 06:04
@thlsn I expect this issue is fixed in v1.21, please check.

**Closed** 2020-08-28 06:05 UTC
Labels: bugfix, fixed, need reproduction

**Comment by thlsn** [comment] 2020-08-28 23:08
> @thlsn I expect this issue is fixed in v1.21, please check.

@lucwastiaux Do you need the record to show the bug? I just saw your comment requesting it.

**Comment by lucwastiaux** [comment] 2020-08-29 00:39
@thlsn no need, the issue is fixed now.

**Comment by lucwastiaux** [comment] 2020-08-29 00:59
@thlsn if this issue was fixed to your satisfaction please leave a review on the addon page: https://ankiweb.net/shared/info/1436550454
