### ISSUE TITLE
On the fly group tts erratic behaviour or not working at all.

### ISSUE THREAD

**Issue by yaoberh** [AwesomeTTS/awesometts-anki-addon#137] opened 2020-10-17 13:36 UTC
I have a deck with 3 language subdecks ordered like this:
Languages:
subdeck------>japanese
subdeck----->chinese
subdeck----->korean

The're ordered in such a way that they appear randomly from each subdeck.
Thing is that for some reason group tts bugs out and doesn't play anything at all. Only when I remove the tts tag and readd it again it works but only until a different language card appears and it stops altogether again.

Any hints?

**Comment by lucwastiaux** [comment] 2020-10-17 13:48
Do all the cards share the same card templates , regardless of the language of the card ? I think this will be problematic, because AwesomeTTS won't know what language is being requested. Did this work well for you on AwesomeTTS 1.22 and previously ?

Ideally could you please share your deck somewhere, I can import it and try to understand what's happening.

Alternatively, is batch-generation an option for you ? It will always work more reliably and give you perfect cross-platform support.

**Comment by yaoberh** [comment] 2020-10-17 13:59
No, they all have different card templates. Working perfectly with awesometts unofficial (no new tts backend implemented yet).
Batch generation is an option but I prefer to have random voices in my learning process, so ideally I'd like to leave on the fly as the primary option. Each card has the tag at the bottom.
My collection:
http://www.mediafire.com/file/146beii9yk6h75b/collection-2020-10-17%254010-54-01.colpkg/file

**Comment by lucwastiaux** [comment] 2020-10-17 14:00
In the immediate term are you able to downgrade awesometts to get you back to a working solution ? I'm going to experiment with your deck and see what's happening, which may take me a few days.

**Comment by yaoberh** [comment] 2020-10-17 14:02
Yeah sure, already done that. In fact I've reverted to the old <tts group> tag and it's working flawlessly. I've even implemented it twice with different fields and it never let me down. Thanks a bunch for your help. The random fonts may be a bother, sorry about that!

**Comment by lucwastiaux** [comment] 2020-10-17 14:05
OK thanks. The new method should work absolutely reliably, so the behavior you're seeing is abnormal and should be fixed. I will get back to you.

**Comment by lucwastiaux** [comment] 2020-10-17 15:12
I think I know what the issue was and I just released 1.25 which I believe should fix this. You will unfortunately have to re-add your TTS tags to perform the language to group association. You will now get a clear error message if playback wasn't successful. Apologies for the bug.

**Comment by yaoberh** [comment] 2020-10-18 17:57
After adding the tags and them working once each, it threw me an error:
AwesomeTTS: Language zh_CN (Chinese (Mandarin, simplified)) not configured for on-the-fly TTS, please add TTS tag in Card template editor to register this language.

**Comment by lucwastiaux** [comment] 2020-10-18 23:18
Did it work once with Chinese and stop working after that? I think I need to add a screen which shows these mappings, to allow the user to verify that everything is correct.

**Comment by yaoberh** [comment] 2020-10-19 12:12
I was thinking that adding a screen would be the best option too. It worked once with all of them but then it stopped. Automatic playback is erratic sometimes too.

**Comment by lucwastiaux** [comment] 2020-10-19 15:03
I can confirm AwesomeTTS 1.25 had a bug where the language to preset association wasn't remembered across restarts. I believe I have now fixed this in AwesomeTTS 1.26. Could I ask you to give it a try and let me know how it goes ?

**Comment by lucwastiaux** [comment] 2020-10-19 15:38
I wrote the following documentation which can potentially clarify certain things https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/On-the-fly-TTS

**Comment by yaoberh** [comment] 2020-10-19 19:12
Seems to be working ok now! I'll report any errors :)

**Comment by yaoberh** [comment] 2020-10-19 21:41
Closing anki and opening it again caused this problem:
AwesomeTTS: Could not play back 栗色の: None of the presets in this group were able to play the input text.

**Comment by lucwastiaux** [comment] 2020-10-20 00:09
Just to confirm, everything is working for you now?

**Comment by yaoberh** [comment] 2020-10-22 13:01
Yep, everything's working perfectly. Didn't see your last message. Sorry!

**Closed** 2020-10-22 13:01 UTC
Labels: bugfix
