### ISSUE TITLE
Yandex.Translate stopped working recently for most languages

### ISSUE THREAD

**Issue by noinkling** [AwesomeTTS/awesometts-anki-addon#28] opened 2017-11-27 23:53 UTC
When I try to preview most languages it gives a 400 error message, including Spanish which I have been using because it is half-decent. Only English, Russian and Turkish work now. I checked the source and it seems you're using the TTS endpoint, and [the docs for that](https://tech.yandex.com/speechkit/cloud/doc/guide/concepts/tts-overview-technology-docpage/) say it only supports those same three languages + Ukrainian (which isn't an option in the addon), so I guess they must have changed things.

[Their translation interface](https://translate.yandex.com) still has TTS for a ton of languages, but it looks like it's using the web speech API - I'm not sure if that has always been the case, but the current Spanish voice from that is definitely different than the one I was getting through this addon.

**Comment by lucwastiaux** [comment] 2020-06-16 13:55
I can confirm spanish is broken on Yandex.  English seems to be working.

**Comment by lucwastiaux** [comment] 2020-10-13 08:30
Closing for now, not enough demand.

**Closed by lucwastiaux** 2020-10-13 08:30 UTC
Labels: fix service

**Comment by jolars** [comment] 2021-12-07 07:13
This is not working for me with Swedish.

![image](https://user-images.githubusercontent.com/13087841/144983270-3ce32b5c-8040-4468-a1e6-afe7a1ed4793.png)
