### ISSUE TITLE
Error while adding new card

### ISSUE THREAD

**Issue by stevencch99** [AwesomeTTS/awesometts-anki-addon#123] opened 2020-08-20 13:14 UTC
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.30 (06a69c25) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-20 00:29:49
Add-ons possibly involved: ⁨AwesomeTTS Google Cloud Text-to-Speech unofficial⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "aqt/editor.py", line 418, in onBridgeCmd
  File "/Users/nine_bro/Library/Application Support/Anki2/addons21/814349176/awesometts/gui/common.py", line 121, in _show
    self._instance = self._target.constructor(
  File "/Users/nine_bro/Library/Application Support/Anki2/addons21/814349176/awesometts/gui/generator.py", line 670, in __init__
    super(EditorGenerator, self).__init__(
  File "/Users/nine_bro/Library/Application Support/Anki2/addons21/814349176/awesometts/gui/base.py", line 243, in __init__
    super(ServiceDialog, self).__init__(*args, **kwargs)
  File "/Users/nine_bro/Library/Application Support/Anki2/addons21/814349176/awesometts/gui/base.py", line 77, in __init__
    super(Dialog, self).__init__(parent)
RuntimeError: wrapped C/C++ object of type Browser has been deleted

**Comment by lucwastiaux** [comment] 2020-08-27 02:35
Can you record a screen capture of what you do which leads to this bug ? i'm unable to reproduce it.

**Comment by stevencch99** [comment] 2020-08-27 03:48
Sure, I'll try to reproduce and record the process.

**Comment by lucwastiaux** [comment] 2020-08-27 03:54
thank you @stevencch99 that'll be extremely useful for me to reproduce, which is the first step towards resolution.

**Comment by stevencch99** [comment] 2020-08-27 18:31
@lucwastiaux I found the way to reproduce this error and made a screen recording for that,
please have a look from my youtube link: <https://youtu.be/iZoMEEw_CUA>

And I want to thank you for the great work, this project really helps me a lot!

**Comment by lucwastiaux** [comment] 2020-08-28 00:34
@stevencch99 thank you for making the video. please remember to regenerate your google API key as it is visible in the video.

**Comment by lucwastiaux** [comment] 2020-08-28 06:02
@stevencch99 I expect this issue is fixed in v1.21, just released. please check.

**Closed** 2020-08-28 06:05 UTC
Labels: bugfix, fixed, need reproduction

**Comment by lucwastiaux** [comment] 2020-08-29 00:57
@stevencch99 please leave a rating on the addon page if this issue was fixed to your satisfaction https://ankiweb.net/shared/info/1436550454
