### ISSUE TITLE
Support for Anki 2.1

### ISSUE THREAD

**Issue by crocket** [AwesomeTTS/awesometts-anki-addon#29] opened 2017-11-30 03:57 UTC
Anki 2.0 is deprecated on Gentoo Linux. If AwesomeTTS was migrated to 2.1, I could install 2.1 on Gentoo LInux.

**Comment by dae** [comment] 2017-12-08 11:27
@felixraumann AnkiWeb supports a separate .zip for 2.1, and it looks like the code has already been ported, so it would be great if you could upload a .zip for 2.1 users. If you're too busy, please let me know and I can share a 2.1-only version until you're ready.

**Comment by crocket** [comment] 2017-12-08 22:22
I'm not in hurry because I can use anki 2.0 for a while. I'll wait until AwesomeTTS for anki 2.1 is uploaded.

**Comment by dae** [comment] 2017-12-22 00:52
@felixraumann I've uploaded a temporary 2.1 version here: https://ankiweb.net/shared/info/900455869
There were only minor changes: https://github.com/dae/awesometts-anki-addon/commit/532bcc59d8b8b350ce8d67b85828241c9a5146f7

**Comment by krassowski** [comment] 2018-01-20 15:23
A bit of a duplicate of #14, I guess :)

Anyway, I was using the ported version (without the @dae's workarounds actually) for more than a month and haven't had much of a problem with it other than a nuance with exception handling, fixed in #30.

@felixraumann I think that uploading the 2.1-compatible version now would be a good move (as 2.1 is still in the beta - and it would be easier to polish the add-on once we get feedback from more users; I also hope that the changes in beta will slow down finally)

**Closed** 2020-06-14 14:30 UTC
